#!/usr/local/bin/perl

use CGI qw(:standard);
use Sys::Hostname;
use strict;

print header();


my $APACHE = "/opt/software/apache2";

my $flagVirtualHost = 0;
my %servers;

my $hostname;
my $serverName;
my $IPAddress;
my $documentRoot;
my $accessLog;
my $errorLog;

my $server;

$hostname = hostname();

open (CONF, "$APACHE/conf/extra/httpd-vhosts.conf") || die "cannot open $APACHE/conf/extra/httpd-vhosts.conf";

while (<CONF>) {
	chomp;

	if (/^<VirtualHost (.*)>/) {
		$flagVirtualHost = 1;
		$IPAddress = $1;
	}
	elsif ($flagVirtualHost == 1 && /^\s*ServerName\s*(.*)/) {
		$serverName = $1;
		$servers{$serverName}->{IPAddress} = $IPAddress;
	}
	elsif ($flagVirtualHost == 1 && /^\s*DocumentRoot\s*(.*)/) {
		$documentRoot= $1;
		$servers{$serverName}->{documentRoot} = $documentRoot;
	}
	elsif ($flagVirtualHost == 1 && /^\s*CustomLog\s*(.*)\s*(common|combined)/) {
		$accessLog = $1;
		$servers{$serverName}->{accessLog} = $accessLog;
	}
	elsif ($flagVirtualHost == 1 && /^\s*ErrorLog\s*(.*)/) {
		$errorLog = $1;
		$servers{$serverName}->{errorLog} = $errorLog;
	}
	elsif ($flagVirtualHost == 1 && /^<\/VirtualHost>/) {
		$flagVirtualHost = 0;
	}
}

close CONF;

print <<EOF;
<HTML>
<HEAD>
<TITLE>
</TITLE>
</HEAD>
<BODY>
Apache web servers on $hostname:
<P>
<TABLE BORDER=1 CELLSPACING=0>
<TR>
<TH>Server</TH>
<TH>DocumentRoot</TH>
<TH>AccessLog</TH>
<TH>ErrorLog</TH>
</TR>
EOF

for $server (sort keys %servers) {
	print "<tr>\n";
	if ($servers{$server}->{IPAddress} !~ /:443$/ ) {
		print "<td><a href=\"http://$server\">http://$server</a></td>\n";
	} else {
		print "<td><a href=\"https://$server\">https://$server</a></td>\n";
	}
	print "<td>$servers{$server}->{documentRoot}</td>\n";
	print "<td><a href=\"http://$server/cgi-bin/getweblogs?servername=$server&logtype=access\">access log</a></td>\n";
	print "<td><a href=\"http://$server/cgi-bin/getweblogs?servername=$server&logtype=error\">error log</a></td>\n";
	print "<tr>\n";
}

print <<EOF;
</TABLE>
</BODY>
</HTML>
EOF
